force-app/main/default/objects/VisualCrossingCredentials__c/VisualCrossingCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Visual Crossing Credentials</label>
</CustomObject>

force-app/main/default/objects/VisualCrossingCredentials__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>API Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisualCrossingCredentials__c/fields/UnitGroup__c.field-meta.xml
<CustomField>
    <fullName>UnitGroup__c</fullName>
    <label>UnitGroup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalloutService.cls
public with sharing class CalloutService {

    public static String getWeatherByLocation(String location){
        HttpRequest req = new HttpRequest();
        VisualCrossingCredentials__c credential = VisualCrossingCredentials__c.getInstance('Default');
        String unitGroup = credential.UnitGroup__c;
        String apiKey = credential.APIKey__c;
        String contentType = credential.ContentType__c;
        req.setEndPoint(credential.Endpoint__c + location + '?unitGroup='+unitGroup +
                                                            '&key=' + apiKey +
                                                            '&contentType=' + contentType);
        req.setMethod('GET');
        Http http = new Http();
        HTTPResponse res = http.send(req);
        
       return res.getBody();
       
       
    }
    
}