force-app/main/default/objects/VisualCrossingCredentials__c/VisualCrossingCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Visual Crossing Credentials</label>
</CustomObject>

force-app/main/default/objects/VisualCrossingCredentials__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>API Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VisualCrossingCredentials__c/fields/UnitGroup__c.field-meta.xml
<CustomField>
    <fullName>UnitGroup__c</fullName>
    <label>UnitGroup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VisualCrossingControllerTest.cls
@isTest
public with sharing class VisualCrossingControllerTest {

    @TestSetup
    static void makeCredentials(){
        VisualCrossingCredentials__c vsc = new VisualCrossingCredentials__c();
        vsc.UnitGroup__c = 'metrics';
        vsc.ContentType__c = 'json';
        vsc.APIKey__c = 'sample';
        vsc.Name = 'Default';
        insert vsc;
    }


    @isTest
    public static void test(){
        Test.setMock(HttpCalloutMock.class, new MockCallout());
        Test.startTest();
        VisualCrossingController.getWeatherByLocation('London');
        Test.stopTest();
    }

}